# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
    ]
