# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('mood_level', models.IntegerField(default=5)),
                ('has_headaches', models.BooleanField(default=False)),
                ('other_diseases', models.TextField(default=None, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('group', models.CharField(default=None, max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reports.Report')),
            ],
        ),
    ]
