# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('group', models.CharField(default=None, max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.AddField(
            model_name='report',
            name='has_headaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='mood_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='report',
            name='other_diseases',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
