# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 22:26
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Message = apps.get_model('msg', 'Message')
    Message.objects.all().delete()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
