# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_auto_20161208_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('datetime',)},
        ),
    ]
